name: Deploy Lambda function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Zip Lambda function code
        run: |
          cd /path/to/api-lambda
          zip -r /path/to/api-lambda.zip *
      - name: Deploy Lambda function
        run: |
          aws cloudformation deploy \
            --template-file /path/to/template.yml \
            --stack-name my-lambda-stack \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
