name: Deploy Lambda Function

on:
  push:
    branches:
      - feature/cloudformation-and-github-action-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Zip code
      run: |
        (cd cloud-formation/api-lambda; zip -r ../api-lambda.zip *;)

    - name: Deploy function
      run: |
        aws cloudformation deploy --template-file cloud-formation/cloudformation.yml --stack-name pascal-test-geolocator-api --capabilities CAPABILITY_IAM --region ca-central-1
        aws lambda update-function-code --function-name pascal-test-geolocator-api --zip-file fileb://cloud-formation/api-lambda.zip
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key}}
        AWS_SESSION_TOKEN: ${{ secrets.aws_session_token}}
